---
- name: Copy xscreensaver config
  ansible.builtin.copy:
    src: "xscreensaver"
    dest: "/home/{{ ansible_user }}/.xscreensaver"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
...
