---
- name: Install the last version of asciidoc-tools
  ansible.builtin.package:
    name:
      - "asciidoc"
      - "asciidoctor"
      - "gnuplot"
      - "xdot"
      - "jre-openjdk-headless"
    state: latest

- name: Install latest available version of asciidoctor-diagram
  community.general.gem:
    name: asciidoctor-diagram
    state: latest
...
