---
- name: Install the last version of vim
  ansible.builtin.package:
    name: "vim"
    state: latest

- name: Copy vimrc
  ansible.builtin.copy:
    src: "vimrc"
    dest: "/home/{{ ansible_user }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Copy vim folder
  ansible.builtin.copy:
    src: "vim"
    dest: "/home/{{ ansible_user }}/.config/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Create a .vim directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.vim/autoload"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Upload the plugin manager via get url
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ ansible_user }}/.vim/autoload/plug.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
...
